import type {
  Student,
  StaffMember,
  LeaveRequest,
  FeeRecord,
  FeeCategory,
  HostelRoom,
  HostelComplaint,
  HostelVisitor,
  LibraryBook,
  BookCirculation,
  BusRoute,
  Announcement,
  SupportTicket,
  ExamSchedule,
  TimetableEntry,
  Assignment,
  AttendanceRecord,
  PaymentTransaction,
  CalendarEvent,
  SyllabusModule,
  StudyMaterial,
} from "./store";

export function getInitialStore() {
  return {
    students: seedStudents,
    staff: seedStaff,
    leaveRequests: seedLeaves,
    feeRecords: seedFees,
    feeCategories: seedFeeCategories,
    hostelRooms: seedRooms,
    hostelComplaints: seedComplaints,
    hostelVisitors: seedVisitors,
    libraryBooks: seedBooks,
    bookCirculations: seedCirculations,
    busRoutes: seedBusRoutes,
    announcements: seedAnnouncements,
    supportTickets: seedTickets,
    examSchedules: seedExams,
    timetableEntries: seedTimetable,
    assignments: seedAssignments,
    attendanceRecords: seedAttendance,
    paymentTransactions: seedPayments,
    calendarEvents: seedCalendar,
    chatMessages: [],
    syllabusModules: seedSyllabus,
    studyMaterials: seedMaterials,
  };
}

const seedStudents: Student[] = [
  {
    id: "s1",
    name: "Aarav Sharma",
    grade: "10",
    section: "A",
    rollNo: "1001",
    email: "aarav@school.com",
    phone: "9876543210",
    guardian: "Mr. Rajesh Sharma",
    address: "12, MG Road, Pune",
    attendance: 92,
    feesPaid: 45000,
    feesDue: 12400,
    status: "active",
  },
  {
    id: "s2",
    name: "Diya Patel",
    grade: "10",
    section: "A",
    rollNo: "1002",
    email: "diya@school.com",
    phone: "9876543211",
    guardian: "Mrs. Neha Patel",
    address: "45, Park Street, Pune",
    attendance: 96,
    feesPaid: 57400,
    feesDue: 0,
    status: "active",
  },
  {
    id: "s3",
    name: "Rohan Verma",
    grade: "10",
    section: "B",
    rollNo: "1003",
    email: "rohan@school.com",
    phone: "9876543212",
    guardian: "Mr. Sunil Verma",
    address: "78, Lake View, Pune",
    attendance: 78,
    feesPaid: 30000,
    feesDue: 27400,
    status: "active",
  },
  {
    id: "s4",
    name: "Ananya Singh",
    grade: "9",
    section: "A",
    rollNo: "901",
    email: "ananya@school.com",
    phone: "9876543213",
    guardian: "Dr. Meera Singh",
    address: "23, Hill Road, Pune",
    attendance: 88,
    feesPaid: 50000,
    feesDue: 7400,
    status: "active",
  },
  {
    id: "s5",
    name: "Kabir Mehta",
    grade: "9",
    section: "B",
    rollNo: "902",
    email: "kabir@school.com",
    phone: "9876543214",
    guardian: "Mr. Anil Mehta",
    address: "56, River Lane, Pune",
    attendance: 84,
    feesPaid: 40000,
    feesDue: 17400,
    status: "active",
  },
  {
    id: "s6",
    name: "Ishita Nair",
    grade: "10",
    section: "C",
    rollNo: "1004",
    email: "ishita@school.com",
    phone: "9876543215",
    guardian: "Mrs. Lata Nair",
    address: "89, Garden Colony, Pune",
    attendance: 95,
    feesPaid: 57400,
    feesDue: 0,
    status: "active",
  },
  {
    id: "s7",
    name: "Vivaan Joshi",
    grade: "9",
    section: "A",
    rollNo: "903",
    email: "vivaan@school.com",
    phone: "9876543216",
    guardian: "Mr. Prakash Joshi",
    address: "34, Temple Road, Pune",
    attendance: 71,
    feesPaid: 25000,
    feesDue: 32400,
    status: "active",
  },
  {
    id: "s8",
    name: "Myra Kulkarni",
    grade: "10",
    section: "B",
    rollNo: "1005",
    email: "myra@school.com",
    phone: "9876543217",
    guardian: "Dr. Arun Kulkarni",
    address: "67, College Road, Pune",
    attendance: 90,
    feesPaid: 48000,
    feesDue: 9400,
    status: "active",
  },
];

const seedStaff: StaffMember[] = [
  {
    id: "t1",
    name: "Anita Iyer",
    role: "Teacher",
    department: "Mathematics",
    email: "anita@school.com",
    phone: "9988776601",
    joinDate: "2018-06-15",
    salary: 65000,
    status: "active",
    attendance: 97,
  },
  {
    id: "t2",
    name: "Rajesh Rao",
    role: "Teacher",
    department: "Physics",
    email: "rajesh@school.com",
    phone: "9988776602",
    joinDate: "2019-08-01",
    salary: 60000,
    status: "active",
    attendance: 94,
  },
  {
    id: "t3",
    name: "Sunita Singh",
    role: "Teacher",
    department: "English",
    email: "sunita@school.com",
    phone: "9988776603",
    joinDate: "2017-04-10",
    salary: 62000,
    status: "active",
    attendance: 96,
  },
  {
    id: "t4",
    name: "Amit Khan",
    role: "Teacher",
    department: "Chemistry",
    email: "amit@school.com",
    phone: "9988776604",
    joinDate: "2020-01-20",
    salary: 58000,
    status: "active",
    attendance: 92,
  },
  {
    id: "t5",
    name: "Priya Desai",
    role: "Teacher",
    department: "History",
    email: "priya.d@school.com",
    phone: "9988776605",
    joinDate: "2016-07-01",
    salary: 64000,
    status: "active",
    attendance: 98,
  },
  {
    id: "t6",
    name: "Rahul Iyer",
    role: "Lab Assistant",
    department: "Science",
    email: "rahul@school.com",
    phone: "9988776606",
    joinDate: "2021-03-15",
    salary: 35000,
    status: "on-leave",
    attendance: 88,
  },
  {
    id: "t7",
    name: "Meena Sharma",
    role: "Librarian",
    department: "Library",
    email: "meena@school.com",
    phone: "9988776607",
    joinDate: "2015-09-01",
    salary: 42000,
    status: "active",
    attendance: 99,
  },
  {
    id: "t8",
    name: "Vikram Patil",
    role: "Admin Staff",
    department: "Administration",
    email: "vikram@school.com",
    phone: "9988776608",
    joinDate: "2019-11-01",
    salary: 38000,
    status: "active",
    attendance: 95,
  },
];

const seedLeaves: LeaveRequest[] = [
  {
    id: "l1",
    staffId: "t6",
    staffName: "Rahul Iyer",
    type: "Medical",
    from: "2025-05-12",
    to: "2025-05-16",
    reason: "Fever and flu",
    status: "approved",
    appliedOn: "2025-05-10",
  },
  {
    id: "l2",
    staffId: "t2",
    staffName: "Rajesh Rao",
    type: "Casual",
    from: "2025-05-19",
    to: "2025-05-19",
    reason: "Personal work",
    status: "pending",
    appliedOn: "2025-05-14",
  },
  {
    id: "l3",
    staffId: "t3",
    staffName: "Sunita Singh",
    type: "Earned",
    from: "2025-05-22",
    to: "2025-05-26",
    reason: "Family function",
    status: "pending",
    appliedOn: "2025-05-13",
  },
];

const seedFees: FeeRecord[] = [
  {
    id: "f1",
    studentId: "s1",
    studentName: "Aarav Sharma",
    grade: "10",
    category: "Tuition",
    amount: 57400,
    paid: 45000,
    due: 12400,
    dueDate: "2025-06-05",
    status: "partial",
  },
  {
    id: "f2",
    studentId: "s2",
    studentName: "Diya Patel",
    grade: "10",
    category: "Tuition",
    amount: 57400,
    paid: 57400,
    due: 0,
    dueDate: "2025-06-05",
    status: "paid",
  },
  {
    id: "f3",
    studentId: "s3",
    studentName: "Rohan Verma",
    grade: "10",
    category: "Tuition",
    amount: 57400,
    paid: 30000,
    due: 27400,
    dueDate: "2025-05-01",
    status: "overdue",
  },
  {
    id: "f4",
    studentId: "s4",
    studentName: "Ananya Singh",
    grade: "9",
    category: "Tuition",
    amount: 57400,
    paid: 50000,
    due: 7400,
    dueDate: "2025-06-05",
    status: "partial",
  },
  {
    id: "f5",
    studentId: "s5",
    studentName: "Kabir Mehta",
    grade: "9",
    category: "Tuition",
    amount: 57400,
    paid: 40000,
    due: 17400,
    dueDate: "2025-05-15",
    status: "overdue",
  },
  {
    id: "f6",
    studentId: "s7",
    studentName: "Vivaan Joshi",
    grade: "9",
    category: "Tuition",
    amount: 57400,
    paid: 25000,
    due: 32400,
    dueDate: "2025-05-01",
    status: "overdue",
  },
];

const seedFeeCategories: FeeCategory[] = [
  {
    id: "fc1",
    name: "Tuition Fee",
    amount: 45000,
    frequency: "Annual",
    description: "Core academic tuition",
  },
  {
    id: "fc2",
    name: "Lab Fee",
    amount: 5000,
    frequency: "Annual",
    description: "Science and computer lab usage",
  },
  {
    id: "fc3",
    name: "Library Fee",
    amount: 2400,
    frequency: "Annual",
    description: "Library access and resources",
  },
  {
    id: "fc4",
    name: "Transport Fee",
    amount: 18000,
    frequency: "Annual",
    description: "School bus service",
  },
  {
    id: "fc5",
    name: "Sports Fee",
    amount: 3000,
    frequency: "Annual",
    description: "Sports facilities and equipment",
  },
];

const seedRooms: HostelRoom[] = [
  {
    id: "r1",
    block: "A",
    roomNo: "101",
    capacity: 4,
    occupied: 3,
    students: ["s1", "s3", "s5"],
    status: "available",
  },
  {
    id: "r2",
    block: "A",
    roomNo: "102",
    capacity: 4,
    occupied: 4,
    students: ["s2", "s4", "s6", "s8"],
    status: "full",
  },
  {
    id: "r3",
    block: "B",
    roomNo: "201",
    capacity: 3,
    occupied: 2,
    students: ["s7"],
    status: "available",
  },
  {
    id: "r4",
    block: "B",
    roomNo: "202",
    capacity: 3,
    occupied: 0,
    students: [],
    status: "maintenance",
  },
  { id: "r5", block: "C", roomNo: "301", capacity: 4, occupied: 4, students: [], status: "full" },
  {
    id: "r6",
    block: "C",
    roomNo: "302",
    capacity: 4,
    occupied: 1,
    students: [],
    status: "available",
  },
];

const seedComplaints: HostelComplaint[] = [
  {
    id: "hc1",
    studentName: "Aarav Sharma",
    room: "A-101",
    category: "Plumbing",
    description: "Bathroom tap leaking continuously",
    status: "open",
    createdAt: "2025-05-12",
  },
  {
    id: "hc2",
    studentName: "Rohan Verma",
    room: "A-101",
    category: "Electrical",
    description: "Fan not working properly",
    status: "in-progress",
    createdAt: "2025-05-10",
  },
  {
    id: "hc3",
    studentName: "Kabir Mehta",
    room: "A-101",
    category: "Pest Control",
    description: "Ant infestation in room corner",
    status: "resolved",
    createdAt: "2025-05-05",
  },
];

const seedVisitors: HostelVisitor[] = [
  {
    id: "hv1",
    visitorName: "Mr. Rajesh Sharma",
    studentName: "Aarav Sharma",
    room: "A-101",
    purpose: "Parent visit",
    checkIn: "2025-05-14 10:00",
    checkOut: "2025-05-14 12:30",
    status: "checked-out",
  },
  {
    id: "hv2",
    visitorName: "Mrs. Neha Patel",
    studentName: "Diya Patel",
    room: "A-102",
    purpose: "Birthday celebration",
    checkIn: "2025-05-14 14:00",
    checkOut: "",
    status: "checked-in",
  },
];

const seedBooks: LibraryBook[] = [
  {
    id: "b1",
    title: "Calculus: Early Transcendentals",
    author: "James Stewart",
    isbn: "978-1285741550",
    category: "Mathematics",
    totalCopies: 10,
    available: 6,
    shelf: "M-01",
  },
  {
    id: "b2",
    title: "Concepts of Physics Vol. 1",
    author: "H.C. Verma",
    isbn: "978-8177091878",
    category: "Physics",
    totalCopies: 15,
    available: 8,
    shelf: "P-01",
  },
  {
    id: "b3",
    title: "Organic Chemistry",
    author: "Morrison & Boyd",
    isbn: "978-0136436690",
    category: "Chemistry",
    totalCopies: 8,
    available: 3,
    shelf: "C-01",
  },
  {
    id: "b4",
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    isbn: "978-0061120084",
    category: "Literature",
    totalCopies: 12,
    available: 9,
    shelf: "L-01",
  },
  {
    id: "b5",
    title: "A Brief History of Time",
    author: "Stephen Hawking",
    isbn: "978-0553380163",
    category: "Science",
    totalCopies: 6,
    available: 2,
    shelf: "S-01",
  },
  {
    id: "b6",
    title: "The Story of My Experiments with Truth",
    author: "M.K. Gandhi",
    isbn: "978-8172345266",
    category: "History",
    totalCopies: 5,
    available: 4,
    shelf: "H-01",
  },
];

const seedCirculations: BookCirculation[] = [
  {
    id: "bc1",
    bookId: "b1",
    bookTitle: "Calculus: Early Transcendentals",
    studentName: "Aarav Sharma",
    issuedDate: "2025-05-01",
    dueDate: "2025-05-15",
    returnedDate: "",
    status: "overdue",
  },
  {
    id: "bc2",
    bookId: "b2",
    bookTitle: "Concepts of Physics Vol. 1",
    studentName: "Diya Patel",
    issuedDate: "2025-05-10",
    dueDate: "2025-05-24",
    returnedDate: "",
    status: "issued",
  },
  {
    id: "bc3",
    bookId: "b4",
    bookTitle: "To Kill a Mockingbird",
    studentName: "Ananya Singh",
    issuedDate: "2025-05-05",
    dueDate: "2025-05-19",
    returnedDate: "2025-05-14",
    status: "returned",
  },
];

const seedBusRoutes: BusRoute[] = [
  {
    id: "br1",
    routeNo: "R-12",
    driver: "Suresh Kumar",
    phone: "9900110011",
    busNo: "MH-12-AB-1234",
    capacity: 50,
    students: 38,
    currentLat: 18.5204,
    currentLng: 73.8567,
    stops: [
      { name: "Main Gate", time: "07:30", lat: 18.5204, lng: 73.8567 },
      { name: "Sector 8", time: "07:45", lat: 18.528, lng: 73.849 },
      { name: "City Center", time: "08:00", lat: 18.535, lng: 73.84 },
      { name: "School", time: "08:20", lat: 18.545, lng: 73.835 },
    ],
  },
  {
    id: "br2",
    routeNo: "R-15",
    driver: "Manoj Patil",
    phone: "9900110022",
    busNo: "MH-12-CD-5678",
    capacity: 45,
    students: 32,
    currentLat: 18.51,
    currentLng: 73.87,
    stops: [
      { name: "Station Road", time: "07:20", lat: 18.51, lng: 73.87 },
      { name: "Market Square", time: "07:40", lat: 18.518, lng: 73.862 },
      { name: "School", time: "08:10", lat: 18.545, lng: 73.835 },
    ],
  },
];

const seedAnnouncements: Announcement[] = [
  {
    id: "a1",
    title: "Annual Sports Day",
    content: "Annual sports day scheduled for May 28. All students must register by May 20.",
    author: "Principal",
    date: "2025-05-14",
    target: "all",
    priority: "important",
  },
  {
    id: "a2",
    title: "Parent-Teacher Meeting",
    content: "PTM for grades 9-10 on May 22 from 10 AM to 1 PM.",
    author: "Admin",
    date: "2025-05-13",
    target: "all",
    priority: "normal",
  },
  {
    id: "a3",
    title: "Library Holiday Notice",
    content: "Library will remain closed on May 17 for inventory audit.",
    author: "Librarian",
    date: "2025-05-12",
    target: "all",
    priority: "normal",
  },
  {
    id: "a4",
    title: "Fee Payment Deadline",
    content: "Last date for fee payment without late charge is June 5.",
    author: "Accounts",
    date: "2025-05-10",
    target: "students",
    priority: "urgent",
  },
];

const seedTickets: SupportTicket[] = [
  {
    id: "tk1",
    title: "Projector not working in Room 201",
    description: "The ceiling projector shows no signal when connected.",
    category: "IT Equipment",
    submittedBy: "Anita Iyer",
    status: "open",
    priority: "high",
    createdAt: "2025-05-13",
    responses: [],
  },
  {
    id: "tk2",
    title: "Wi-Fi connectivity issue in Block B",
    description: "Students unable to connect to campus Wi-Fi since morning.",
    category: "Network",
    submittedBy: "Rajesh Rao",
    status: "in-progress",
    priority: "high",
    createdAt: "2025-05-12",
    responses: [
      {
        author: "IT Support",
        message: "We are investigating the router in Block B.",
        date: "2025-05-12",
      },
    ],
  },
  {
    id: "tk3",
    title: "New software installation request",
    description: "Need MATLAB installed in Computer Lab 2.",
    category: "Software",
    submittedBy: "Amit Khan",
    status: "resolved",
    priority: "medium",
    createdAt: "2025-05-08",
    responses: [
      {
        author: "IT Support",
        message: "MATLAB has been installed on all 30 machines.",
        date: "2025-05-10",
      },
    ],
  },
];

const seedExams: ExamSchedule[] = [
  {
    id: "e1",
    name: "Pre-Final",
    subject: "Mathematics",
    grade: "10",
    date: "2025-05-26",
    startTime: "09:00",
    endTime: "12:00",
    room: "Hall-1",
  },
  {
    id: "e2",
    name: "Pre-Final",
    subject: "Physics",
    grade: "10",
    date: "2025-05-28",
    startTime: "09:00",
    endTime: "12:00",
    room: "Hall-1",
  },
  {
    id: "e3",
    name: "Pre-Final",
    subject: "English",
    grade: "10",
    date: "2025-05-30",
    startTime: "09:00",
    endTime: "11:30",
    room: "Hall-2",
  },
  {
    id: "e4",
    name: "Pre-Final",
    subject: "Chemistry",
    grade: "10",
    date: "2025-06-02",
    startTime: "09:00",
    endTime: "12:00",
    room: "Lab-1",
  },
  {
    id: "e5",
    name: "Unit Test 3",
    subject: "Mathematics",
    grade: "9",
    date: "2025-05-20",
    startTime: "10:00",
    endTime: "11:00",
    room: "204",
  },
];

const seedTimetable: TimetableEntry[] = [
  {
    id: "tt1",
    day: "Monday",
    time: "08:30",
    subject: "Mathematics",
    teacher: "Anita Iyer",
    room: "201",
    grade: "10",
    section: "A",
  },
  {
    id: "tt2",
    day: "Monday",
    time: "09:30",
    subject: "Physics",
    teacher: "Rajesh Rao",
    room: "Lab-2",
    grade: "10",
    section: "A",
  },
  {
    id: "tt3",
    day: "Monday",
    time: "10:30",
    subject: "English",
    teacher: "Sunita Singh",
    room: "108",
    grade: "10",
    section: "A",
  },
  {
    id: "tt4",
    day: "Monday",
    time: "11:45",
    subject: "Chemistry",
    teacher: "Amit Khan",
    room: "Lab-1",
    grade: "10",
    section: "A",
  },
  {
    id: "tt5",
    day: "Monday",
    time: "12:45",
    subject: "History",
    teacher: "Priya Desai",
    room: "204",
    grade: "10",
    section: "A",
  },
  {
    id: "tt6",
    day: "Tuesday",
    time: "08:30",
    subject: "English",
    teacher: "Sunita Singh",
    room: "108",
    grade: "10",
    section: "A",
  },
  {
    id: "tt7",
    day: "Tuesday",
    time: "09:30",
    subject: "Mathematics",
    teacher: "Anita Iyer",
    room: "201",
    grade: "10",
    section: "A",
  },
  {
    id: "tt8",
    day: "Tuesday",
    time: "10:30",
    subject: "Chemistry",
    teacher: "Amit Khan",
    room: "Lab-1",
    grade: "10",
    section: "A",
  },
  {
    id: "tt9",
    day: "Wednesday",
    time: "08:30",
    subject: "Physics",
    teacher: "Rajesh Rao",
    room: "Lab-2",
    grade: "10",
    section: "A",
  },
  {
    id: "tt10",
    day: "Wednesday",
    time: "09:30",
    subject: "History",
    teacher: "Priya Desai",
    room: "204",
    grade: "10",
    section: "A",
  },
];

const seedAssignments: Assignment[] = [
  {
    id: "as1",
    title: "Quadratic Equations — Set 4",
    subject: "Mathematics",
    grade: "10",
    description: "Solve all problems from exercise 4.3 and 4.4",
    dueDate: "2025-05-16",
    createdBy: "Anita Iyer",
    attachments: [],
    maxScore: 50,
    submissions: [
      {
        id: "sub1",
        studentName: "Aarav Sharma",
        studentId: "s1",
        submittedAt: "",
        files: [],
        score: null,
        feedback: "",
        status: "submitted",
      },
      {
        id: "sub2",
        studentName: "Diya Patel",
        studentId: "s2",
        submittedAt: "2025-05-14",
        files: ["quadratic_solutions.pdf"],
        score: 45,
        feedback: "Excellent work!",
        status: "graded",
      },
    ],
  },
  {
    id: "as2",
    title: "Lab Report: Reflection of Light",
    subject: "Physics",
    grade: "10",
    description: "Write a detailed lab report on the reflection experiment conducted in class.",
    dueDate: "2025-05-18",
    createdBy: "Rajesh Rao",
    attachments: [],
    maxScore: 30,
    submissions: [],
  },
  {
    id: "as3",
    title: "Essay on Climate Change",
    subject: "English",
    grade: "10",
    description: "Write a 500-word essay on the impact of climate change.",
    dueDate: "2025-05-20",
    createdBy: "Sunita Singh",
    attachments: [],
    maxScore: 25,
    submissions: [
      {
        id: "sub3",
        studentName: "Aarav Sharma",
        studentId: "s1",
        submittedAt: "2025-05-13",
        files: ["essay_climate.pdf"],
        score: 22,
        feedback: "Well structured arguments.",
        status: "graded",
      },
    ],
  },
];

const seedAttendance: AttendanceRecord[] = [
  {
    id: "at1",
    date: "2025-05-14",
    grade: "10",
    section: "A",
    markedBy: "Anita Iyer",
    records: [
      { studentId: "s1", studentName: "Aarav Sharma", status: "present" },
      { studentId: "s2", studentName: "Diya Patel", status: "present" },
      { studentId: "s3", studentName: "Rohan Verma", status: "absent" },
      { studentId: "s6", studentName: "Ishita Nair", status: "present" },
      { studentId: "s8", studentName: "Myra Kulkarni", status: "late" },
    ],
  },
];

const seedPayments: PaymentTransaction[] = [
  {
    id: "pay1",
    studentId: "s1",
    studentName: "Aarav Sharma",
    amount: 15000,
    date: "2025-04-15",
    method: "Online",
    receiptNo: "RCP-2025-001",
    category: "Tuition",
    status: "success",
  },
  {
    id: "pay2",
    studentId: "s1",
    studentName: "Aarav Sharma",
    amount: 30000,
    date: "2025-03-01",
    method: "Bank Transfer",
    receiptNo: "RCP-2025-002",
    category: "Tuition",
    status: "success",
  },
  {
    id: "pay3",
    studentId: "s2",
    studentName: "Diya Patel",
    amount: 57400,
    date: "2025-04-01",
    method: "Online",
    receiptNo: "RCP-2025-003",
    category: "Tuition",
    status: "success",
  },
];

const seedCalendar: CalendarEvent[] = [
  {
    id: "ce1",
    title: "Unit Test 3 — Mathematics",
    date: "2025-05-20",
    type: "exam",
    description: "Grade 9 unit test",
  },
  {
    id: "ce2",
    title: "PTM",
    date: "2025-05-22",
    type: "event",
    description: "Parent-Teacher Meeting for grades 9-10",
  },
  {
    id: "ce3",
    title: "Pre-Final — Mathematics",
    date: "2025-05-26",
    type: "exam",
    description: "Grade 10 pre-final exam",
  },
  {
    id: "ce4",
    title: "Annual Sports Day",
    date: "2025-05-28",
    type: "event",
    description: "School-wide sports competition",
  },
  {
    id: "ce5",
    title: "Summer Vacation Begins",
    date: "2025-06-10",
    type: "holiday",
    description: "School closes for summer break",
  },
  {
    id: "ce6",
    title: "Fee Payment Deadline",
    date: "2025-06-05",
    type: "deadline",
    description: "Last date without late charge",
  },
];

const seedSyllabus: SyllabusModule[] = [
  {
    id: "sy1",
    subject: "Mathematics",
    grade: "10",
    unit: "Quadratic Equations",
    topics: [
      "Standard form",
      "Factorization",
      "Completing the square",
      "Quadratic formula",
      "Nature of roots",
    ],
    completed: true,
  },
  {
    id: "sy2",
    subject: "Mathematics",
    grade: "10",
    unit: "Arithmetic Progressions",
    topics: ["nth term", "Sum of n terms", "Applications"],
    completed: true,
  },
  {
    id: "sy3",
    subject: "Mathematics",
    grade: "10",
    unit: "Probability",
    topics: ["Classical probability", "Complementary events", "Impossible & Sure events"],
    completed: false,
  },
  {
    id: "sy4",
    subject: "Science",
    grade: "10",
    unit: "Light — Reflection",
    topics: ["Laws of reflection", "Plane mirrors", "Spherical mirrors", "Mirror formula"],
    completed: true,
  },
  {
    id: "sy5",
    subject: "Science",
    grade: "10",
    unit: "Chemical Reactions",
    topics: ["Types of reactions", "Balancing equations", "Oxidation-Reduction"],
    completed: false,
  },
  {
    id: "sy6",
    subject: "Chemistry",
    grade: "10",
    unit: "Periodic Table",
    topics: ["Modern periodic table", "Trends", "Valency", "Atomic size"],
    completed: false,
  },
];

const seedMaterials: StudyMaterial[] = [
  {
    id: "sm1",
    title: "Quadratic Equations — Notes",
    subject: "Mathematics",
    grade: "10",
    type: "pdf",
    uploadedBy: "Anita Iyer",
    uploadDate: "2025-05-01",
    size: "2.4 MB",
    downloaded: false,
  },
  {
    id: "sm2",
    title: "Physics Lab Manual",
    subject: "Physics",
    grade: "10",
    type: "pdf",
    uploadedBy: "Rajesh Rao",
    uploadDate: "2025-04-28",
    size: "5.1 MB",
    downloaded: false,
  },
  {
    id: "sm3",
    title: "English Grammar Reference",
    subject: "English",
    grade: "10",
    type: "doc",
    uploadedBy: "Sunita Singh",
    uploadDate: "2025-04-25",
    size: "1.8 MB",
    downloaded: true,
  },
  {
    id: "sm4",
    title: "Chemical Bonding — Video Lecture",
    subject: "Chemistry",
    grade: "10",
    type: "video",
    uploadedBy: "Amit Khan",
    uploadDate: "2025-05-05",
    size: "120 MB",
    downloaded: false,
  },
];
