/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as StudentRouteImport } from './routes/student'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeacherIndexRouteImport } from './routes/teacher.index'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TeacherSyllabusRouteImport } from './routes/teacher.syllabus'
import { Route as TeacherSupportRouteImport } from './routes/teacher.support'
import { Route as TeacherReportsRouteImport } from './routes/teacher.reports'
import { Route as TeacherProfileRouteImport } from './routes/teacher.profile'
import { Route as TeacherMessagesRouteImport } from './routes/teacher.messages'
import { Route as TeacherMaterialsRouteImport } from './routes/teacher.materials'
import { Route as TeacherLeaveRouteImport } from './routes/teacher.leave'
import { Route as TeacherFeesRouteImport } from './routes/teacher.fees'
import { Route as TeacherFeedRouteImport } from './routes/teacher.feed'
import { Route as TeacherExamsRouteImport } from './routes/teacher.exams'
import { Route as TeacherAttendanceRouteImport } from './routes/teacher.attendance'
import { Route as TeacherAssignmentsRouteImport } from './routes/teacher.assignments'
import { Route as StudentTransportRouteImport } from './routes/student.transport'
import { Route as StudentTimetableRouteImport } from './routes/student.timetable'
import { Route as StudentSyllabusRouteImport } from './routes/student.syllabus'
import { Route as StudentProfileRouteImport } from './routes/student.profile'
import { Route as StudentNotificationsRouteImport } from './routes/student.notifications'
import { Route as StudentMaterialsRouteImport } from './routes/student.materials'
import { Route as StudentFeesRouteImport } from './routes/student.fees'
import { Route as StudentFeedRouteImport } from './routes/student.feed'
import { Route as StudentCalendarRouteImport } from './routes/student.calendar'
import { Route as StudentAssignmentsRouteImport } from './routes/student.assignments'
import { Route as StudentAiHubRouteImport } from './routes/student.ai-hub'
import { Route as StudentAcademicsRouteImport } from './routes/student.academics'
import { Route as AdminTransportRouteImport } from './routes/admin.transport'
import { Route as AdminStudentsRouteImport } from './routes/admin.students'
import { Route as AdminStaffRouteImport } from './routes/admin.staff'
import { Route as AdminLibraryRouteImport } from './routes/admin.library'
import { Route as AdminHrRouteImport } from './routes/admin.hr'
import { Route as AdminHostelRouteImport } from './routes/admin.hostel'
import { Route as AdminFeesRouteImport } from './routes/admin.fees'
import { Route as AdminExamsRouteImport } from './routes/admin.exams'
import { Route as AdminCommunicationsRouteImport } from './routes/admin.communications'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminAiHubRouteImport } from './routes/admin.ai-hub'
import { Route as AdminAcademicsRouteImport } from './routes/admin.academics'

const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherIndexRoute = TeacherIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeacherRoute,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TeacherSyllabusRoute = TeacherSyllabusRouteImport.update({
  id: '/syllabus',
  path: '/syllabus',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherSupportRoute = TeacherSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherReportsRoute = TeacherReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherProfileRoute = TeacherProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherMessagesRoute = TeacherMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherMaterialsRoute = TeacherMaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherLeaveRoute = TeacherLeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherFeesRoute = TeacherFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherFeedRoute = TeacherFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherExamsRoute = TeacherExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherAttendanceRoute = TeacherAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherAssignmentsRoute = TeacherAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => TeacherRoute,
} as any)
const StudentTransportRoute = StudentTransportRouteImport.update({
  id: '/transport',
  path: '/transport',
  getParentRoute: () => StudentRoute,
} as any)
const StudentTimetableRoute = StudentTimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => StudentRoute,
} as any)
const StudentSyllabusRoute = StudentSyllabusRouteImport.update({
  id: '/syllabus',
  path: '/syllabus',
  getParentRoute: () => StudentRoute,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StudentRoute,
} as any)
const StudentNotificationsRoute = StudentNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => StudentRoute,
} as any)
const StudentMaterialsRoute = StudentMaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => StudentRoute,
} as any)
const StudentFeesRoute = StudentFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => StudentRoute,
} as any)
const StudentFeedRoute = StudentFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => StudentRoute,
} as any)
const StudentCalendarRoute = StudentCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => StudentRoute,
} as any)
const StudentAssignmentsRoute = StudentAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => StudentRoute,
} as any)
const StudentAiHubRoute = StudentAiHubRouteImport.update({
  id: '/ai-hub',
  path: '/ai-hub',
  getParentRoute: () => StudentRoute,
} as any)
const StudentAcademicsRoute = StudentAcademicsRouteImport.update({
  id: '/academics',
  path: '/academics',
  getParentRoute: () => StudentRoute,
} as any)
const AdminTransportRoute = AdminTransportRouteImport.update({
  id: '/transport',
  path: '/transport',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLibraryRoute = AdminLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHrRoute = AdminHrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHostelRoute = AdminHostelRouteImport.update({
  id: '/hostel',
  path: '/hostel',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeesRoute = AdminFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExamsRoute = AdminExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommunicationsRoute = AdminCommunicationsRouteImport.update({
  id: '/communications',
  path: '/communications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiHubRoute = AdminAiHubRouteImport.update({
  id: '/ai-hub',
  path: '/ai-hub',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAcademicsRoute = AdminAcademicsRouteImport.update({
  id: '/academics',
  path: '/academics',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/admin/academics': typeof AdminAcademicsRoute
  '/admin/ai-hub': typeof AdminAiHubRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/communications': typeof AdminCommunicationsRoute
  '/admin/exams': typeof AdminExamsRoute
  '/admin/fees': typeof AdminFeesRoute
  '/admin/hostel': typeof AdminHostelRoute
  '/admin/hr': typeof AdminHrRoute
  '/admin/library': typeof AdminLibraryRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/transport': typeof AdminTransportRoute
  '/student/academics': typeof StudentAcademicsRoute
  '/student/ai-hub': typeof StudentAiHubRoute
  '/student/assignments': typeof StudentAssignmentsRoute
  '/student/calendar': typeof StudentCalendarRoute
  '/student/feed': typeof StudentFeedRoute
  '/student/fees': typeof StudentFeesRoute
  '/student/materials': typeof StudentMaterialsRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/syllabus': typeof StudentSyllabusRoute
  '/student/timetable': typeof StudentTimetableRoute
  '/student/transport': typeof StudentTransportRoute
  '/teacher/assignments': typeof TeacherAssignmentsRoute
  '/teacher/attendance': typeof TeacherAttendanceRoute
  '/teacher/exams': typeof TeacherExamsRoute
  '/teacher/feed': typeof TeacherFeedRoute
  '/teacher/fees': typeof TeacherFeesRoute
  '/teacher/leave': typeof TeacherLeaveRoute
  '/teacher/materials': typeof TeacherMaterialsRoute
  '/teacher/messages': typeof TeacherMessagesRoute
  '/teacher/profile': typeof TeacherProfileRoute
  '/teacher/reports': typeof TeacherReportsRoute
  '/teacher/support': typeof TeacherSupportRoute
  '/teacher/syllabus': typeof TeacherSyllabusRoute
  '/admin/': typeof AdminIndexRoute
  '/student/': typeof StudentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/academics': typeof AdminAcademicsRoute
  '/admin/ai-hub': typeof AdminAiHubRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/communications': typeof AdminCommunicationsRoute
  '/admin/exams': typeof AdminExamsRoute
  '/admin/fees': typeof AdminFeesRoute
  '/admin/hostel': typeof AdminHostelRoute
  '/admin/hr': typeof AdminHrRoute
  '/admin/library': typeof AdminLibraryRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/transport': typeof AdminTransportRoute
  '/student/academics': typeof StudentAcademicsRoute
  '/student/ai-hub': typeof StudentAiHubRoute
  '/student/assignments': typeof StudentAssignmentsRoute
  '/student/calendar': typeof StudentCalendarRoute
  '/student/feed': typeof StudentFeedRoute
  '/student/fees': typeof StudentFeesRoute
  '/student/materials': typeof StudentMaterialsRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/syllabus': typeof StudentSyllabusRoute
  '/student/timetable': typeof StudentTimetableRoute
  '/student/transport': typeof StudentTransportRoute
  '/teacher/assignments': typeof TeacherAssignmentsRoute
  '/teacher/attendance': typeof TeacherAttendanceRoute
  '/teacher/exams': typeof TeacherExamsRoute
  '/teacher/feed': typeof TeacherFeedRoute
  '/teacher/fees': typeof TeacherFeesRoute
  '/teacher/leave': typeof TeacherLeaveRoute
  '/teacher/materials': typeof TeacherMaterialsRoute
  '/teacher/messages': typeof TeacherMessagesRoute
  '/teacher/profile': typeof TeacherProfileRoute
  '/teacher/reports': typeof TeacherReportsRoute
  '/teacher/support': typeof TeacherSupportRoute
  '/teacher/syllabus': typeof TeacherSyllabusRoute
  '/admin': typeof AdminIndexRoute
  '/student': typeof StudentIndexRoute
  '/teacher': typeof TeacherIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/admin/academics': typeof AdminAcademicsRoute
  '/admin/ai-hub': typeof AdminAiHubRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/communications': typeof AdminCommunicationsRoute
  '/admin/exams': typeof AdminExamsRoute
  '/admin/fees': typeof AdminFeesRoute
  '/admin/hostel': typeof AdminHostelRoute
  '/admin/hr': typeof AdminHrRoute
  '/admin/library': typeof AdminLibraryRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/transport': typeof AdminTransportRoute
  '/student/academics': typeof StudentAcademicsRoute
  '/student/ai-hub': typeof StudentAiHubRoute
  '/student/assignments': typeof StudentAssignmentsRoute
  '/student/calendar': typeof StudentCalendarRoute
  '/student/feed': typeof StudentFeedRoute
  '/student/fees': typeof StudentFeesRoute
  '/student/materials': typeof StudentMaterialsRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/syllabus': typeof StudentSyllabusRoute
  '/student/timetable': typeof StudentTimetableRoute
  '/student/transport': typeof StudentTransportRoute
  '/teacher/assignments': typeof TeacherAssignmentsRoute
  '/teacher/attendance': typeof TeacherAttendanceRoute
  '/teacher/exams': typeof TeacherExamsRoute
  '/teacher/feed': typeof TeacherFeedRoute
  '/teacher/fees': typeof TeacherFeesRoute
  '/teacher/leave': typeof TeacherLeaveRoute
  '/teacher/materials': typeof TeacherMaterialsRoute
  '/teacher/messages': typeof TeacherMessagesRoute
  '/teacher/profile': typeof TeacherProfileRoute
  '/teacher/reports': typeof TeacherReportsRoute
  '/teacher/support': typeof TeacherSupportRoute
  '/teacher/syllabus': typeof TeacherSyllabusRoute
  '/admin/': typeof AdminIndexRoute
  '/student/': typeof StudentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/student'
    | '/teacher'
    | '/admin/academics'
    | '/admin/ai-hub'
    | '/admin/analytics'
    | '/admin/communications'
    | '/admin/exams'
    | '/admin/fees'
    | '/admin/hostel'
    | '/admin/hr'
    | '/admin/library'
    | '/admin/staff'
    | '/admin/students'
    | '/admin/transport'
    | '/student/academics'
    | '/student/ai-hub'
    | '/student/assignments'
    | '/student/calendar'
    | '/student/feed'
    | '/student/fees'
    | '/student/materials'
    | '/student/notifications'
    | '/student/profile'
    | '/student/syllabus'
    | '/student/timetable'
    | '/student/transport'
    | '/teacher/assignments'
    | '/teacher/attendance'
    | '/teacher/exams'
    | '/teacher/feed'
    | '/teacher/fees'
    | '/teacher/leave'
    | '/teacher/materials'
    | '/teacher/messages'
    | '/teacher/profile'
    | '/teacher/reports'
    | '/teacher/support'
    | '/teacher/syllabus'
    | '/admin/'
    | '/student/'
    | '/teacher/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/academics'
    | '/admin/ai-hub'
    | '/admin/analytics'
    | '/admin/communications'
    | '/admin/exams'
    | '/admin/fees'
    | '/admin/hostel'
    | '/admin/hr'
    | '/admin/library'
    | '/admin/staff'
    | '/admin/students'
    | '/admin/transport'
    | '/student/academics'
    | '/student/ai-hub'
    | '/student/assignments'
    | '/student/calendar'
    | '/student/feed'
    | '/student/fees'
    | '/student/materials'
    | '/student/notifications'
    | '/student/profile'
    | '/student/syllabus'
    | '/student/timetable'
    | '/student/transport'
    | '/teacher/assignments'
    | '/teacher/attendance'
    | '/teacher/exams'
    | '/teacher/feed'
    | '/teacher/fees'
    | '/teacher/leave'
    | '/teacher/materials'
    | '/teacher/messages'
    | '/teacher/profile'
    | '/teacher/reports'
    | '/teacher/support'
    | '/teacher/syllabus'
    | '/admin'
    | '/student'
    | '/teacher'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/student'
    | '/teacher'
    | '/admin/academics'
    | '/admin/ai-hub'
    | '/admin/analytics'
    | '/admin/communications'
    | '/admin/exams'
    | '/admin/fees'
    | '/admin/hostel'
    | '/admin/hr'
    | '/admin/library'
    | '/admin/staff'
    | '/admin/students'
    | '/admin/transport'
    | '/student/academics'
    | '/student/ai-hub'
    | '/student/assignments'
    | '/student/calendar'
    | '/student/feed'
    | '/student/fees'
    | '/student/materials'
    | '/student/notifications'
    | '/student/profile'
    | '/student/syllabus'
    | '/student/timetable'
    | '/student/transport'
    | '/teacher/assignments'
    | '/teacher/attendance'
    | '/teacher/exams'
    | '/teacher/feed'
    | '/teacher/fees'
    | '/teacher/leave'
    | '/teacher/materials'
    | '/teacher/messages'
    | '/teacher/profile'
    | '/teacher/reports'
    | '/teacher/support'
    | '/teacher/syllabus'
    | '/admin/'
    | '/student/'
    | '/teacher/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  StudentRoute: typeof StudentRouteWithChildren
  TeacherRoute: typeof TeacherRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/': {
      id: '/teacher/'
      path: '/'
      fullPath: '/teacher/'
      preLoaderRoute: typeof TeacherIndexRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/teacher/syllabus': {
      id: '/teacher/syllabus'
      path: '/syllabus'
      fullPath: '/teacher/syllabus'
      preLoaderRoute: typeof TeacherSyllabusRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/support': {
      id: '/teacher/support'
      path: '/support'
      fullPath: '/teacher/support'
      preLoaderRoute: typeof TeacherSupportRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/reports': {
      id: '/teacher/reports'
      path: '/reports'
      fullPath: '/teacher/reports'
      preLoaderRoute: typeof TeacherReportsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/profile': {
      id: '/teacher/profile'
      path: '/profile'
      fullPath: '/teacher/profile'
      preLoaderRoute: typeof TeacherProfileRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/messages': {
      id: '/teacher/messages'
      path: '/messages'
      fullPath: '/teacher/messages'
      preLoaderRoute: typeof TeacherMessagesRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/materials': {
      id: '/teacher/materials'
      path: '/materials'
      fullPath: '/teacher/materials'
      preLoaderRoute: typeof TeacherMaterialsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/leave': {
      id: '/teacher/leave'
      path: '/leave'
      fullPath: '/teacher/leave'
      preLoaderRoute: typeof TeacherLeaveRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/fees': {
      id: '/teacher/fees'
      path: '/fees'
      fullPath: '/teacher/fees'
      preLoaderRoute: typeof TeacherFeesRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/feed': {
      id: '/teacher/feed'
      path: '/feed'
      fullPath: '/teacher/feed'
      preLoaderRoute: typeof TeacherFeedRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/exams': {
      id: '/teacher/exams'
      path: '/exams'
      fullPath: '/teacher/exams'
      preLoaderRoute: typeof TeacherExamsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/attendance': {
      id: '/teacher/attendance'
      path: '/attendance'
      fullPath: '/teacher/attendance'
      preLoaderRoute: typeof TeacherAttendanceRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/assignments': {
      id: '/teacher/assignments'
      path: '/assignments'
      fullPath: '/teacher/assignments'
      preLoaderRoute: typeof TeacherAssignmentsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/student/transport': {
      id: '/student/transport'
      path: '/transport'
      fullPath: '/student/transport'
      preLoaderRoute: typeof StudentTransportRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/timetable': {
      id: '/student/timetable'
      path: '/timetable'
      fullPath: '/student/timetable'
      preLoaderRoute: typeof StudentTimetableRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/syllabus': {
      id: '/student/syllabus'
      path: '/syllabus'
      fullPath: '/student/syllabus'
      preLoaderRoute: typeof StudentSyllabusRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/notifications': {
      id: '/student/notifications'
      path: '/notifications'
      fullPath: '/student/notifications'
      preLoaderRoute: typeof StudentNotificationsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/materials': {
      id: '/student/materials'
      path: '/materials'
      fullPath: '/student/materials'
      preLoaderRoute: typeof StudentMaterialsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/fees': {
      id: '/student/fees'
      path: '/fees'
      fullPath: '/student/fees'
      preLoaderRoute: typeof StudentFeesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/feed': {
      id: '/student/feed'
      path: '/feed'
      fullPath: '/student/feed'
      preLoaderRoute: typeof StudentFeedRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/calendar': {
      id: '/student/calendar'
      path: '/calendar'
      fullPath: '/student/calendar'
      preLoaderRoute: typeof StudentCalendarRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/assignments': {
      id: '/student/assignments'
      path: '/assignments'
      fullPath: '/student/assignments'
      preLoaderRoute: typeof StudentAssignmentsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/ai-hub': {
      id: '/student/ai-hub'
      path: '/ai-hub'
      fullPath: '/student/ai-hub'
      preLoaderRoute: typeof StudentAiHubRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/academics': {
      id: '/student/academics'
      path: '/academics'
      fullPath: '/student/academics'
      preLoaderRoute: typeof StudentAcademicsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/admin/transport': {
      id: '/admin/transport'
      path: '/transport'
      fullPath: '/admin/transport'
      preLoaderRoute: typeof AdminTransportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/staff': {
      id: '/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AdminStaffRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/library': {
      id: '/admin/library'
      path: '/library'
      fullPath: '/admin/library'
      preLoaderRoute: typeof AdminLibraryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/hr': {
      id: '/admin/hr'
      path: '/hr'
      fullPath: '/admin/hr'
      preLoaderRoute: typeof AdminHrRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/hostel': {
      id: '/admin/hostel'
      path: '/hostel'
      fullPath: '/admin/hostel'
      preLoaderRoute: typeof AdminHostelRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/fees': {
      id: '/admin/fees'
      path: '/fees'
      fullPath: '/admin/fees'
      preLoaderRoute: typeof AdminFeesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/exams': {
      id: '/admin/exams'
      path: '/exams'
      fullPath: '/admin/exams'
      preLoaderRoute: typeof AdminExamsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/communications': {
      id: '/admin/communications'
      path: '/communications'
      fullPath: '/admin/communications'
      preLoaderRoute: typeof AdminCommunicationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ai-hub': {
      id: '/admin/ai-hub'
      path: '/ai-hub'
      fullPath: '/admin/ai-hub'
      preLoaderRoute: typeof AdminAiHubRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/academics': {
      id: '/admin/academics'
      path: '/academics'
      fullPath: '/admin/academics'
      preLoaderRoute: typeof AdminAcademicsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAcademicsRoute: typeof AdminAcademicsRoute
  AdminAiHubRoute: typeof AdminAiHubRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminCommunicationsRoute: typeof AdminCommunicationsRoute
  AdminExamsRoute: typeof AdminExamsRoute
  AdminFeesRoute: typeof AdminFeesRoute
  AdminHostelRoute: typeof AdminHostelRoute
  AdminHrRoute: typeof AdminHrRoute
  AdminLibraryRoute: typeof AdminLibraryRoute
  AdminStaffRoute: typeof AdminStaffRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminTransportRoute: typeof AdminTransportRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAcademicsRoute: AdminAcademicsRoute,
  AdminAiHubRoute: AdminAiHubRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCommunicationsRoute: AdminCommunicationsRoute,
  AdminExamsRoute: AdminExamsRoute,
  AdminFeesRoute: AdminFeesRoute,
  AdminHostelRoute: AdminHostelRoute,
  AdminHrRoute: AdminHrRoute,
  AdminLibraryRoute: AdminLibraryRoute,
  AdminStaffRoute: AdminStaffRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminTransportRoute: AdminTransportRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface StudentRouteChildren {
  StudentAcademicsRoute: typeof StudentAcademicsRoute
  StudentAiHubRoute: typeof StudentAiHubRoute
  StudentAssignmentsRoute: typeof StudentAssignmentsRoute
  StudentCalendarRoute: typeof StudentCalendarRoute
  StudentFeedRoute: typeof StudentFeedRoute
  StudentFeesRoute: typeof StudentFeesRoute
  StudentMaterialsRoute: typeof StudentMaterialsRoute
  StudentNotificationsRoute: typeof StudentNotificationsRoute
  StudentProfileRoute: typeof StudentProfileRoute
  StudentSyllabusRoute: typeof StudentSyllabusRoute
  StudentTimetableRoute: typeof StudentTimetableRoute
  StudentTransportRoute: typeof StudentTransportRoute
  StudentIndexRoute: typeof StudentIndexRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentAcademicsRoute: StudentAcademicsRoute,
  StudentAiHubRoute: StudentAiHubRoute,
  StudentAssignmentsRoute: StudentAssignmentsRoute,
  StudentCalendarRoute: StudentCalendarRoute,
  StudentFeedRoute: StudentFeedRoute,
  StudentFeesRoute: StudentFeesRoute,
  StudentMaterialsRoute: StudentMaterialsRoute,
  StudentNotificationsRoute: StudentNotificationsRoute,
  StudentProfileRoute: StudentProfileRoute,
  StudentSyllabusRoute: StudentSyllabusRoute,
  StudentTimetableRoute: StudentTimetableRoute,
  StudentTransportRoute: StudentTransportRoute,
  StudentIndexRoute: StudentIndexRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

interface TeacherRouteChildren {
  TeacherAssignmentsRoute: typeof TeacherAssignmentsRoute
  TeacherAttendanceRoute: typeof TeacherAttendanceRoute
  TeacherExamsRoute: typeof TeacherExamsRoute
  TeacherFeedRoute: typeof TeacherFeedRoute
  TeacherFeesRoute: typeof TeacherFeesRoute
  TeacherLeaveRoute: typeof TeacherLeaveRoute
  TeacherMaterialsRoute: typeof TeacherMaterialsRoute
  TeacherMessagesRoute: typeof TeacherMessagesRoute
  TeacherProfileRoute: typeof TeacherProfileRoute
  TeacherReportsRoute: typeof TeacherReportsRoute
  TeacherSupportRoute: typeof TeacherSupportRoute
  TeacherSyllabusRoute: typeof TeacherSyllabusRoute
  TeacherIndexRoute: typeof TeacherIndexRoute
}

const TeacherRouteChildren: TeacherRouteChildren = {
  TeacherAssignmentsRoute: TeacherAssignmentsRoute,
  TeacherAttendanceRoute: TeacherAttendanceRoute,
  TeacherExamsRoute: TeacherExamsRoute,
  TeacherFeedRoute: TeacherFeedRoute,
  TeacherFeesRoute: TeacherFeesRoute,
  TeacherLeaveRoute: TeacherLeaveRoute,
  TeacherMaterialsRoute: TeacherMaterialsRoute,
  TeacherMessagesRoute: TeacherMessagesRoute,
  TeacherProfileRoute: TeacherProfileRoute,
  TeacherReportsRoute: TeacherReportsRoute,
  TeacherSupportRoute: TeacherSupportRoute,
  TeacherSyllabusRoute: TeacherSyllabusRoute,
  TeacherIndexRoute: TeacherIndexRoute,
}

const TeacherRouteWithChildren =
  TeacherRoute._addFileChildren(TeacherRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  StudentRoute: StudentRouteWithChildren,
  TeacherRoute: TeacherRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
