/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as SuperAdminRouteImport } from './routes/super-admin'
import { Route as StudentRouteImport } from './routes/student'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ParentRouteImport } from './routes/parent'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeacherIndexRouteImport } from './routes/teacher.index'
import { Route as SuperAdminIndexRouteImport } from './routes/super-admin.index'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as ParentIndexRouteImport } from './routes/parent.index'
import { Route as DriverIndexRouteImport } from './routes/driver.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TeacherSyllabusRouteImport } from './routes/teacher.syllabus'
import { Route as TeacherSupportRouteImport } from './routes/teacher.support'
import { Route as TeacherReportsRouteImport } from './routes/teacher.reports'
import { Route as TeacherProfileRouteImport } from './routes/teacher.profile'
import { Route as TeacherMessagesRouteImport } from './routes/teacher.messages'
import { Route as TeacherMaterialsRouteImport } from './routes/teacher.materials'
import { Route as TeacherLiveClassRouteImport } from './routes/teacher.live-class'
import { Route as TeacherLeaveRouteImport } from './routes/teacher.leave'
import { Route as TeacherFeesRouteImport } from './routes/teacher.fees'
import { Route as TeacherFeedRouteImport } from './routes/teacher.feed'
import { Route as TeacherExamsRouteImport } from './routes/teacher.exams'
import { Route as TeacherAttendanceRouteImport } from './routes/teacher.attendance'
import { Route as TeacherAssignmentsRouteImport } from './routes/teacher.assignments'
import { Route as TeacherAiHubRouteImport } from './routes/teacher.ai-hub'
import { Route as SuperAdminHelpdeskRouteImport } from './routes/super-admin.helpdesk'
import { Route as SuperAdminDirectoryRouteImport } from './routes/super-admin.directory'
import { Route as SuperAdminConfigRouteImport } from './routes/super-admin.config'
import { Route as StudentTransportRouteImport } from './routes/student.transport'
import { Route as StudentTimetableRouteImport } from './routes/student.timetable'
import { Route as StudentSyllabusRouteImport } from './routes/student.syllabus'
import { Route as StudentProfileRouteImport } from './routes/student.profile'
import { Route as StudentNotificationsRouteImport } from './routes/student.notifications'
import { Route as StudentMaterialsRouteImport } from './routes/student.materials'
import { Route as StudentFeesRouteImport } from './routes/student.fees'
import { Route as StudentFeedRouteImport } from './routes/student.feed'
import { Route as StudentCalendarRouteImport } from './routes/student.calendar'
import { Route as StudentAssignmentsRouteImport } from './routes/student.assignments'
import { Route as StudentAiHubRouteImport } from './routes/student.ai-hub'
import { Route as StudentAcademicsRouteImport } from './routes/student.academics'
import { Route as ParentTransportRouteImport } from './routes/parent.transport'
import { Route as ParentNotificationsRouteImport } from './routes/parent.notifications'
import { Route as ParentFeesRouteImport } from './routes/parent.fees'
import { Route as ParentAdmissionsRouteImport } from './routes/parent.admissions'
import { Route as ParentAcademicsRouteImport } from './routes/parent.academics'
import { Route as AdminVisitorsRouteImport } from './routes/admin.visitors'
import { Route as AdminTransportRouteImport } from './routes/admin.transport'
import { Route as AdminStudentsRouteImport } from './routes/admin.students'
import { Route as AdminStaffRouteImport } from './routes/admin.staff'
import { Route as AdminSportsRouteImport } from './routes/admin.sports'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSafetyRouteImport } from './routes/admin.safety'
import { Route as AdminLibraryRouteImport } from './routes/admin.library'
import { Route as AdminInventoryRouteImport } from './routes/admin.inventory'
import { Route as AdminHrRouteImport } from './routes/admin.hr'
import { Route as AdminHostelRouteImport } from './routes/admin.hostel'
import { Route as AdminHealthRouteImport } from './routes/admin.health'
import { Route as AdminFeesRouteImport } from './routes/admin.fees'
import { Route as AdminExamsRouteImport } from './routes/admin.exams'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminCommunicationsRouteImport } from './routes/admin.communications'
import { Route as AdminCertificatesRouteImport } from './routes/admin.certificates'
import { Route as AdminCanteenRouteImport } from './routes/admin.canteen'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminAiHubRouteImport } from './routes/admin.ai-hub'
import { Route as AdminAdmissionsRouteImport } from './routes/admin.admissions'
import { Route as AdminAcademicsRouteImport } from './routes/admin.academics'

const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminRoute = SuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentRoute = ParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherIndexRoute = TeacherIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeacherRoute,
} as any)
const SuperAdminIndexRoute = SuperAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuperAdminRoute,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const ParentIndexRoute = ParentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ParentRoute,
} as any)
const DriverIndexRoute = DriverIndexRouteImport.update({
  id: '/driver/',
  path: '/driver/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TeacherSyllabusRoute = TeacherSyllabusRouteImport.update({
  id: '/syllabus',
  path: '/syllabus',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherSupportRoute = TeacherSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherReportsRoute = TeacherReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherProfileRoute = TeacherProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherMessagesRoute = TeacherMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherMaterialsRoute = TeacherMaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherLiveClassRoute = TeacherLiveClassRouteImport.update({
  id: '/live-class',
  path: '/live-class',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherLeaveRoute = TeacherLeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherFeesRoute = TeacherFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherFeedRoute = TeacherFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherExamsRoute = TeacherExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherAttendanceRoute = TeacherAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherAssignmentsRoute = TeacherAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherAiHubRoute = TeacherAiHubRouteImport.update({
  id: '/ai-hub',
  path: '/ai-hub',
  getParentRoute: () => TeacherRoute,
} as any)
const SuperAdminHelpdeskRoute = SuperAdminHelpdeskRouteImport.update({
  id: '/helpdesk',
  path: '/helpdesk',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminDirectoryRoute = SuperAdminDirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminConfigRoute = SuperAdminConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => SuperAdminRoute,
} as any)
const StudentTransportRoute = StudentTransportRouteImport.update({
  id: '/transport',
  path: '/transport',
  getParentRoute: () => StudentRoute,
} as any)
const StudentTimetableRoute = StudentTimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => StudentRoute,
} as any)
const StudentSyllabusRoute = StudentSyllabusRouteImport.update({
  id: '/syllabus',
  path: '/syllabus',
  getParentRoute: () => StudentRoute,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StudentRoute,
} as any)
const StudentNotificationsRoute = StudentNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => StudentRoute,
} as any)
const StudentMaterialsRoute = StudentMaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => StudentRoute,
} as any)
const StudentFeesRoute = StudentFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => StudentRoute,
} as any)
const StudentFeedRoute = StudentFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => StudentRoute,
} as any)
const StudentCalendarRoute = StudentCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => StudentRoute,
} as any)
const StudentAssignmentsRoute = StudentAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => StudentRoute,
} as any)
const StudentAiHubRoute = StudentAiHubRouteImport.update({
  id: '/ai-hub',
  path: '/ai-hub',
  getParentRoute: () => StudentRoute,
} as any)
const StudentAcademicsRoute = StudentAcademicsRouteImport.update({
  id: '/academics',
  path: '/academics',
  getParentRoute: () => StudentRoute,
} as any)
const ParentTransportRoute = ParentTransportRouteImport.update({
  id: '/transport',
  path: '/transport',
  getParentRoute: () => ParentRoute,
} as any)
const ParentNotificationsRoute = ParentNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => ParentRoute,
} as any)
const ParentFeesRoute = ParentFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => ParentRoute,
} as any)
const ParentAdmissionsRoute = ParentAdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => ParentRoute,
} as any)
const ParentAcademicsRoute = ParentAcademicsRouteImport.update({
  id: '/academics',
  path: '/academics',
  getParentRoute: () => ParentRoute,
} as any)
const AdminVisitorsRoute = AdminVisitorsRouteImport.update({
  id: '/visitors',
  path: '/visitors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTransportRoute = AdminTransportRouteImport.update({
  id: '/transport',
  path: '/transport',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSportsRoute = AdminSportsRouteImport.update({
  id: '/sports',
  path: '/sports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSafetyRoute = AdminSafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLibraryRoute = AdminLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHrRoute = AdminHrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHostelRoute = AdminHostelRouteImport.update({
  id: '/hostel',
  path: '/hostel',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHealthRoute = AdminHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeesRoute = AdminFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExamsRoute = AdminExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommunicationsRoute = AdminCommunicationsRouteImport.update({
  id: '/communications',
  path: '/communications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCertificatesRoute = AdminCertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCanteenRoute = AdminCanteenRouteImport.update({
  id: '/canteen',
  path: '/canteen',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiHubRoute = AdminAiHubRouteImport.update({
  id: '/ai-hub',
  path: '/ai-hub',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdmissionsRoute = AdminAdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAcademicsRoute = AdminAcademicsRouteImport.update({
  id: '/academics',
  path: '/academics',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/parent': typeof ParentRouteWithChildren
  '/register': typeof RegisterRoute
  '/student': typeof StudentRouteWithChildren
  '/super-admin': typeof SuperAdminRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/admin/academics': typeof AdminAcademicsRoute
  '/admin/admissions': typeof AdminAdmissionsRoute
  '/admin/ai-hub': typeof AdminAiHubRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/canteen': typeof AdminCanteenRoute
  '/admin/certificates': typeof AdminCertificatesRoute
  '/admin/communications': typeof AdminCommunicationsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/exams': typeof AdminExamsRoute
  '/admin/fees': typeof AdminFeesRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/hostel': typeof AdminHostelRoute
  '/admin/hr': typeof AdminHrRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/library': typeof AdminLibraryRoute
  '/admin/safety': typeof AdminSafetyRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sports': typeof AdminSportsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/transport': typeof AdminTransportRoute
  '/admin/visitors': typeof AdminVisitorsRoute
  '/parent/academics': typeof ParentAcademicsRoute
  '/parent/admissions': typeof ParentAdmissionsRoute
  '/parent/fees': typeof ParentFeesRoute
  '/parent/notifications': typeof ParentNotificationsRoute
  '/parent/transport': typeof ParentTransportRoute
  '/student/academics': typeof StudentAcademicsRoute
  '/student/ai-hub': typeof StudentAiHubRoute
  '/student/assignments': typeof StudentAssignmentsRoute
  '/student/calendar': typeof StudentCalendarRoute
  '/student/feed': typeof StudentFeedRoute
  '/student/fees': typeof StudentFeesRoute
  '/student/materials': typeof StudentMaterialsRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/syllabus': typeof StudentSyllabusRoute
  '/student/timetable': typeof StudentTimetableRoute
  '/student/transport': typeof StudentTransportRoute
  '/super-admin/config': typeof SuperAdminConfigRoute
  '/super-admin/directory': typeof SuperAdminDirectoryRoute
  '/super-admin/helpdesk': typeof SuperAdminHelpdeskRoute
  '/teacher/ai-hub': typeof TeacherAiHubRoute
  '/teacher/assignments': typeof TeacherAssignmentsRoute
  '/teacher/attendance': typeof TeacherAttendanceRoute
  '/teacher/exams': typeof TeacherExamsRoute
  '/teacher/feed': typeof TeacherFeedRoute
  '/teacher/fees': typeof TeacherFeesRoute
  '/teacher/leave': typeof TeacherLeaveRoute
  '/teacher/live-class': typeof TeacherLiveClassRoute
  '/teacher/materials': typeof TeacherMaterialsRoute
  '/teacher/messages': typeof TeacherMessagesRoute
  '/teacher/profile': typeof TeacherProfileRoute
  '/teacher/reports': typeof TeacherReportsRoute
  '/teacher/support': typeof TeacherSupportRoute
  '/teacher/syllabus': typeof TeacherSyllabusRoute
  '/admin/': typeof AdminIndexRoute
  '/driver/': typeof DriverIndexRoute
  '/parent/': typeof ParentIndexRoute
  '/student/': typeof StudentIndexRoute
  '/super-admin/': typeof SuperAdminIndexRoute
  '/teacher/': typeof TeacherIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/academics': typeof AdminAcademicsRoute
  '/admin/admissions': typeof AdminAdmissionsRoute
  '/admin/ai-hub': typeof AdminAiHubRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/canteen': typeof AdminCanteenRoute
  '/admin/certificates': typeof AdminCertificatesRoute
  '/admin/communications': typeof AdminCommunicationsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/exams': typeof AdminExamsRoute
  '/admin/fees': typeof AdminFeesRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/hostel': typeof AdminHostelRoute
  '/admin/hr': typeof AdminHrRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/library': typeof AdminLibraryRoute
  '/admin/safety': typeof AdminSafetyRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sports': typeof AdminSportsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/transport': typeof AdminTransportRoute
  '/admin/visitors': typeof AdminVisitorsRoute
  '/parent/academics': typeof ParentAcademicsRoute
  '/parent/admissions': typeof ParentAdmissionsRoute
  '/parent/fees': typeof ParentFeesRoute
  '/parent/notifications': typeof ParentNotificationsRoute
  '/parent/transport': typeof ParentTransportRoute
  '/student/academics': typeof StudentAcademicsRoute
  '/student/ai-hub': typeof StudentAiHubRoute
  '/student/assignments': typeof StudentAssignmentsRoute
  '/student/calendar': typeof StudentCalendarRoute
  '/student/feed': typeof StudentFeedRoute
  '/student/fees': typeof StudentFeesRoute
  '/student/materials': typeof StudentMaterialsRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/syllabus': typeof StudentSyllabusRoute
  '/student/timetable': typeof StudentTimetableRoute
  '/student/transport': typeof StudentTransportRoute
  '/super-admin/config': typeof SuperAdminConfigRoute
  '/super-admin/directory': typeof SuperAdminDirectoryRoute
  '/super-admin/helpdesk': typeof SuperAdminHelpdeskRoute
  '/teacher/ai-hub': typeof TeacherAiHubRoute
  '/teacher/assignments': typeof TeacherAssignmentsRoute
  '/teacher/attendance': typeof TeacherAttendanceRoute
  '/teacher/exams': typeof TeacherExamsRoute
  '/teacher/feed': typeof TeacherFeedRoute
  '/teacher/fees': typeof TeacherFeesRoute
  '/teacher/leave': typeof TeacherLeaveRoute
  '/teacher/live-class': typeof TeacherLiveClassRoute
  '/teacher/materials': typeof TeacherMaterialsRoute
  '/teacher/messages': typeof TeacherMessagesRoute
  '/teacher/profile': typeof TeacherProfileRoute
  '/teacher/reports': typeof TeacherReportsRoute
  '/teacher/support': typeof TeacherSupportRoute
  '/teacher/syllabus': typeof TeacherSyllabusRoute
  '/admin': typeof AdminIndexRoute
  '/driver': typeof DriverIndexRoute
  '/parent': typeof ParentIndexRoute
  '/student': typeof StudentIndexRoute
  '/super-admin': typeof SuperAdminIndexRoute
  '/teacher': typeof TeacherIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/parent': typeof ParentRouteWithChildren
  '/register': typeof RegisterRoute
  '/student': typeof StudentRouteWithChildren
  '/super-admin': typeof SuperAdminRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/admin/academics': typeof AdminAcademicsRoute
  '/admin/admissions': typeof AdminAdmissionsRoute
  '/admin/ai-hub': typeof AdminAiHubRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/canteen': typeof AdminCanteenRoute
  '/admin/certificates': typeof AdminCertificatesRoute
  '/admin/communications': typeof AdminCommunicationsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/exams': typeof AdminExamsRoute
  '/admin/fees': typeof AdminFeesRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/hostel': typeof AdminHostelRoute
  '/admin/hr': typeof AdminHrRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/library': typeof AdminLibraryRoute
  '/admin/safety': typeof AdminSafetyRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sports': typeof AdminSportsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/transport': typeof AdminTransportRoute
  '/admin/visitors': typeof AdminVisitorsRoute
  '/parent/academics': typeof ParentAcademicsRoute
  '/parent/admissions': typeof ParentAdmissionsRoute
  '/parent/fees': typeof ParentFeesRoute
  '/parent/notifications': typeof ParentNotificationsRoute
  '/parent/transport': typeof ParentTransportRoute
  '/student/academics': typeof StudentAcademicsRoute
  '/student/ai-hub': typeof StudentAiHubRoute
  '/student/assignments': typeof StudentAssignmentsRoute
  '/student/calendar': typeof StudentCalendarRoute
  '/student/feed': typeof StudentFeedRoute
  '/student/fees': typeof StudentFeesRoute
  '/student/materials': typeof StudentMaterialsRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/syllabus': typeof StudentSyllabusRoute
  '/student/timetable': typeof StudentTimetableRoute
  '/student/transport': typeof StudentTransportRoute
  '/super-admin/config': typeof SuperAdminConfigRoute
  '/super-admin/directory': typeof SuperAdminDirectoryRoute
  '/super-admin/helpdesk': typeof SuperAdminHelpdeskRoute
  '/teacher/ai-hub': typeof TeacherAiHubRoute
  '/teacher/assignments': typeof TeacherAssignmentsRoute
  '/teacher/attendance': typeof TeacherAttendanceRoute
  '/teacher/exams': typeof TeacherExamsRoute
  '/teacher/feed': typeof TeacherFeedRoute
  '/teacher/fees': typeof TeacherFeesRoute
  '/teacher/leave': typeof TeacherLeaveRoute
  '/teacher/live-class': typeof TeacherLiveClassRoute
  '/teacher/materials': typeof TeacherMaterialsRoute
  '/teacher/messages': typeof TeacherMessagesRoute
  '/teacher/profile': typeof TeacherProfileRoute
  '/teacher/reports': typeof TeacherReportsRoute
  '/teacher/support': typeof TeacherSupportRoute
  '/teacher/syllabus': typeof TeacherSyllabusRoute
  '/admin/': typeof AdminIndexRoute
  '/driver/': typeof DriverIndexRoute
  '/parent/': typeof ParentIndexRoute
  '/student/': typeof StudentIndexRoute
  '/super-admin/': typeof SuperAdminIndexRoute
  '/teacher/': typeof TeacherIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/parent'
    | '/register'
    | '/student'
    | '/super-admin'
    | '/teacher'
    | '/admin/academics'
    | '/admin/admissions'
    | '/admin/ai-hub'
    | '/admin/analytics'
    | '/admin/canteen'
    | '/admin/certificates'
    | '/admin/communications'
    | '/admin/events'
    | '/admin/exams'
    | '/admin/fees'
    | '/admin/health'
    | '/admin/hostel'
    | '/admin/hr'
    | '/admin/inventory'
    | '/admin/library'
    | '/admin/safety'
    | '/admin/settings'
    | '/admin/sports'
    | '/admin/staff'
    | '/admin/students'
    | '/admin/transport'
    | '/admin/visitors'
    | '/parent/academics'
    | '/parent/admissions'
    | '/parent/fees'
    | '/parent/notifications'
    | '/parent/transport'
    | '/student/academics'
    | '/student/ai-hub'
    | '/student/assignments'
    | '/student/calendar'
    | '/student/feed'
    | '/student/fees'
    | '/student/materials'
    | '/student/notifications'
    | '/student/profile'
    | '/student/syllabus'
    | '/student/timetable'
    | '/student/transport'
    | '/super-admin/config'
    | '/super-admin/directory'
    | '/super-admin/helpdesk'
    | '/teacher/ai-hub'
    | '/teacher/assignments'
    | '/teacher/attendance'
    | '/teacher/exams'
    | '/teacher/feed'
    | '/teacher/fees'
    | '/teacher/leave'
    | '/teacher/live-class'
    | '/teacher/materials'
    | '/teacher/messages'
    | '/teacher/profile'
    | '/teacher/reports'
    | '/teacher/support'
    | '/teacher/syllabus'
    | '/admin/'
    | '/driver/'
    | '/parent/'
    | '/student/'
    | '/super-admin/'
    | '/teacher/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/admin/academics'
    | '/admin/admissions'
    | '/admin/ai-hub'
    | '/admin/analytics'
    | '/admin/canteen'
    | '/admin/certificates'
    | '/admin/communications'
    | '/admin/events'
    | '/admin/exams'
    | '/admin/fees'
    | '/admin/health'
    | '/admin/hostel'
    | '/admin/hr'
    | '/admin/inventory'
    | '/admin/library'
    | '/admin/safety'
    | '/admin/settings'
    | '/admin/sports'
    | '/admin/staff'
    | '/admin/students'
    | '/admin/transport'
    | '/admin/visitors'
    | '/parent/academics'
    | '/parent/admissions'
    | '/parent/fees'
    | '/parent/notifications'
    | '/parent/transport'
    | '/student/academics'
    | '/student/ai-hub'
    | '/student/assignments'
    | '/student/calendar'
    | '/student/feed'
    | '/student/fees'
    | '/student/materials'
    | '/student/notifications'
    | '/student/profile'
    | '/student/syllabus'
    | '/student/timetable'
    | '/student/transport'
    | '/super-admin/config'
    | '/super-admin/directory'
    | '/super-admin/helpdesk'
    | '/teacher/ai-hub'
    | '/teacher/assignments'
    | '/teacher/attendance'
    | '/teacher/exams'
    | '/teacher/feed'
    | '/teacher/fees'
    | '/teacher/leave'
    | '/teacher/live-class'
    | '/teacher/materials'
    | '/teacher/messages'
    | '/teacher/profile'
    | '/teacher/reports'
    | '/teacher/support'
    | '/teacher/syllabus'
    | '/admin'
    | '/driver'
    | '/parent'
    | '/student'
    | '/super-admin'
    | '/teacher'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/parent'
    | '/register'
    | '/student'
    | '/super-admin'
    | '/teacher'
    | '/admin/academics'
    | '/admin/admissions'
    | '/admin/ai-hub'
    | '/admin/analytics'
    | '/admin/canteen'
    | '/admin/certificates'
    | '/admin/communications'
    | '/admin/events'
    | '/admin/exams'
    | '/admin/fees'
    | '/admin/health'
    | '/admin/hostel'
    | '/admin/hr'
    | '/admin/inventory'
    | '/admin/library'
    | '/admin/safety'
    | '/admin/settings'
    | '/admin/sports'
    | '/admin/staff'
    | '/admin/students'
    | '/admin/transport'
    | '/admin/visitors'
    | '/parent/academics'
    | '/parent/admissions'
    | '/parent/fees'
    | '/parent/notifications'
    | '/parent/transport'
    | '/student/academics'
    | '/student/ai-hub'
    | '/student/assignments'
    | '/student/calendar'
    | '/student/feed'
    | '/student/fees'
    | '/student/materials'
    | '/student/notifications'
    | '/student/profile'
    | '/student/syllabus'
    | '/student/timetable'
    | '/student/transport'
    | '/super-admin/config'
    | '/super-admin/directory'
    | '/super-admin/helpdesk'
    | '/teacher/ai-hub'
    | '/teacher/assignments'
    | '/teacher/attendance'
    | '/teacher/exams'
    | '/teacher/feed'
    | '/teacher/fees'
    | '/teacher/leave'
    | '/teacher/live-class'
    | '/teacher/materials'
    | '/teacher/messages'
    | '/teacher/profile'
    | '/teacher/reports'
    | '/teacher/support'
    | '/teacher/syllabus'
    | '/admin/'
    | '/driver/'
    | '/parent/'
    | '/student/'
    | '/super-admin/'
    | '/teacher/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  ParentRoute: typeof ParentRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  StudentRoute: typeof StudentRouteWithChildren
  SuperAdminRoute: typeof SuperAdminRouteWithChildren
  TeacherRoute: typeof TeacherRouteWithChildren
  DriverIndexRoute: typeof DriverIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin': {
      id: '/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent': {
      id: '/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof ParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/': {
      id: '/teacher/'
      path: '/'
      fullPath: '/teacher/'
      preLoaderRoute: typeof TeacherIndexRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/super-admin/': {
      id: '/super-admin/'
      path: '/'
      fullPath: '/super-admin/'
      preLoaderRoute: typeof SuperAdminIndexRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/parent/': {
      id: '/parent/'
      path: '/'
      fullPath: '/parent/'
      preLoaderRoute: typeof ParentIndexRouteImport
      parentRoute: typeof ParentRoute
    }
    '/driver/': {
      id: '/driver/'
      path: '/driver'
      fullPath: '/driver/'
      preLoaderRoute: typeof DriverIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/teacher/syllabus': {
      id: '/teacher/syllabus'
      path: '/syllabus'
      fullPath: '/teacher/syllabus'
      preLoaderRoute: typeof TeacherSyllabusRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/support': {
      id: '/teacher/support'
      path: '/support'
      fullPath: '/teacher/support'
      preLoaderRoute: typeof TeacherSupportRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/reports': {
      id: '/teacher/reports'
      path: '/reports'
      fullPath: '/teacher/reports'
      preLoaderRoute: typeof TeacherReportsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/profile': {
      id: '/teacher/profile'
      path: '/profile'
      fullPath: '/teacher/profile'
      preLoaderRoute: typeof TeacherProfileRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/messages': {
      id: '/teacher/messages'
      path: '/messages'
      fullPath: '/teacher/messages'
      preLoaderRoute: typeof TeacherMessagesRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/materials': {
      id: '/teacher/materials'
      path: '/materials'
      fullPath: '/teacher/materials'
      preLoaderRoute: typeof TeacherMaterialsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/live-class': {
      id: '/teacher/live-class'
      path: '/live-class'
      fullPath: '/teacher/live-class'
      preLoaderRoute: typeof TeacherLiveClassRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/leave': {
      id: '/teacher/leave'
      path: '/leave'
      fullPath: '/teacher/leave'
      preLoaderRoute: typeof TeacherLeaveRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/fees': {
      id: '/teacher/fees'
      path: '/fees'
      fullPath: '/teacher/fees'
      preLoaderRoute: typeof TeacherFeesRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/feed': {
      id: '/teacher/feed'
      path: '/feed'
      fullPath: '/teacher/feed'
      preLoaderRoute: typeof TeacherFeedRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/exams': {
      id: '/teacher/exams'
      path: '/exams'
      fullPath: '/teacher/exams'
      preLoaderRoute: typeof TeacherExamsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/attendance': {
      id: '/teacher/attendance'
      path: '/attendance'
      fullPath: '/teacher/attendance'
      preLoaderRoute: typeof TeacherAttendanceRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/assignments': {
      id: '/teacher/assignments'
      path: '/assignments'
      fullPath: '/teacher/assignments'
      preLoaderRoute: typeof TeacherAssignmentsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/ai-hub': {
      id: '/teacher/ai-hub'
      path: '/ai-hub'
      fullPath: '/teacher/ai-hub'
      preLoaderRoute: typeof TeacherAiHubRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/super-admin/helpdesk': {
      id: '/super-admin/helpdesk'
      path: '/helpdesk'
      fullPath: '/super-admin/helpdesk'
      preLoaderRoute: typeof SuperAdminHelpdeskRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/directory': {
      id: '/super-admin/directory'
      path: '/directory'
      fullPath: '/super-admin/directory'
      preLoaderRoute: typeof SuperAdminDirectoryRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/config': {
      id: '/super-admin/config'
      path: '/config'
      fullPath: '/super-admin/config'
      preLoaderRoute: typeof SuperAdminConfigRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/student/transport': {
      id: '/student/transport'
      path: '/transport'
      fullPath: '/student/transport'
      preLoaderRoute: typeof StudentTransportRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/timetable': {
      id: '/student/timetable'
      path: '/timetable'
      fullPath: '/student/timetable'
      preLoaderRoute: typeof StudentTimetableRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/syllabus': {
      id: '/student/syllabus'
      path: '/syllabus'
      fullPath: '/student/syllabus'
      preLoaderRoute: typeof StudentSyllabusRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/notifications': {
      id: '/student/notifications'
      path: '/notifications'
      fullPath: '/student/notifications'
      preLoaderRoute: typeof StudentNotificationsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/materials': {
      id: '/student/materials'
      path: '/materials'
      fullPath: '/student/materials'
      preLoaderRoute: typeof StudentMaterialsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/fees': {
      id: '/student/fees'
      path: '/fees'
      fullPath: '/student/fees'
      preLoaderRoute: typeof StudentFeesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/feed': {
      id: '/student/feed'
      path: '/feed'
      fullPath: '/student/feed'
      preLoaderRoute: typeof StudentFeedRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/calendar': {
      id: '/student/calendar'
      path: '/calendar'
      fullPath: '/student/calendar'
      preLoaderRoute: typeof StudentCalendarRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/assignments': {
      id: '/student/assignments'
      path: '/assignments'
      fullPath: '/student/assignments'
      preLoaderRoute: typeof StudentAssignmentsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/ai-hub': {
      id: '/student/ai-hub'
      path: '/ai-hub'
      fullPath: '/student/ai-hub'
      preLoaderRoute: typeof StudentAiHubRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/academics': {
      id: '/student/academics'
      path: '/academics'
      fullPath: '/student/academics'
      preLoaderRoute: typeof StudentAcademicsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/parent/transport': {
      id: '/parent/transport'
      path: '/transport'
      fullPath: '/parent/transport'
      preLoaderRoute: typeof ParentTransportRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/notifications': {
      id: '/parent/notifications'
      path: '/notifications'
      fullPath: '/parent/notifications'
      preLoaderRoute: typeof ParentNotificationsRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/fees': {
      id: '/parent/fees'
      path: '/fees'
      fullPath: '/parent/fees'
      preLoaderRoute: typeof ParentFeesRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/admissions': {
      id: '/parent/admissions'
      path: '/admissions'
      fullPath: '/parent/admissions'
      preLoaderRoute: typeof ParentAdmissionsRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/academics': {
      id: '/parent/academics'
      path: '/academics'
      fullPath: '/parent/academics'
      preLoaderRoute: typeof ParentAcademicsRouteImport
      parentRoute: typeof ParentRoute
    }
    '/admin/visitors': {
      id: '/admin/visitors'
      path: '/visitors'
      fullPath: '/admin/visitors'
      preLoaderRoute: typeof AdminVisitorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/transport': {
      id: '/admin/transport'
      path: '/transport'
      fullPath: '/admin/transport'
      preLoaderRoute: typeof AdminTransportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/staff': {
      id: '/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AdminStaffRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sports': {
      id: '/admin/sports'
      path: '/sports'
      fullPath: '/admin/sports'
      preLoaderRoute: typeof AdminSportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/safety': {
      id: '/admin/safety'
      path: '/safety'
      fullPath: '/admin/safety'
      preLoaderRoute: typeof AdminSafetyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/library': {
      id: '/admin/library'
      path: '/library'
      fullPath: '/admin/library'
      preLoaderRoute: typeof AdminLibraryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/hr': {
      id: '/admin/hr'
      path: '/hr'
      fullPath: '/admin/hr'
      preLoaderRoute: typeof AdminHrRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/hostel': {
      id: '/admin/hostel'
      path: '/hostel'
      fullPath: '/admin/hostel'
      preLoaderRoute: typeof AdminHostelRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/health': {
      id: '/admin/health'
      path: '/health'
      fullPath: '/admin/health'
      preLoaderRoute: typeof AdminHealthRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/fees': {
      id: '/admin/fees'
      path: '/fees'
      fullPath: '/admin/fees'
      preLoaderRoute: typeof AdminFeesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/exams': {
      id: '/admin/exams'
      path: '/exams'
      fullPath: '/admin/exams'
      preLoaderRoute: typeof AdminExamsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/communications': {
      id: '/admin/communications'
      path: '/communications'
      fullPath: '/admin/communications'
      preLoaderRoute: typeof AdminCommunicationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/certificates': {
      id: '/admin/certificates'
      path: '/certificates'
      fullPath: '/admin/certificates'
      preLoaderRoute: typeof AdminCertificatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/canteen': {
      id: '/admin/canteen'
      path: '/canteen'
      fullPath: '/admin/canteen'
      preLoaderRoute: typeof AdminCanteenRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ai-hub': {
      id: '/admin/ai-hub'
      path: '/ai-hub'
      fullPath: '/admin/ai-hub'
      preLoaderRoute: typeof AdminAiHubRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/admissions': {
      id: '/admin/admissions'
      path: '/admissions'
      fullPath: '/admin/admissions'
      preLoaderRoute: typeof AdminAdmissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/academics': {
      id: '/admin/academics'
      path: '/academics'
      fullPath: '/admin/academics'
      preLoaderRoute: typeof AdminAcademicsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAcademicsRoute: typeof AdminAcademicsRoute
  AdminAdmissionsRoute: typeof AdminAdmissionsRoute
  AdminAiHubRoute: typeof AdminAiHubRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminCanteenRoute: typeof AdminCanteenRoute
  AdminCertificatesRoute: typeof AdminCertificatesRoute
  AdminCommunicationsRoute: typeof AdminCommunicationsRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminExamsRoute: typeof AdminExamsRoute
  AdminFeesRoute: typeof AdminFeesRoute
  AdminHealthRoute: typeof AdminHealthRoute
  AdminHostelRoute: typeof AdminHostelRoute
  AdminHrRoute: typeof AdminHrRoute
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminLibraryRoute: typeof AdminLibraryRoute
  AdminSafetyRoute: typeof AdminSafetyRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSportsRoute: typeof AdminSportsRoute
  AdminStaffRoute: typeof AdminStaffRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminTransportRoute: typeof AdminTransportRoute
  AdminVisitorsRoute: typeof AdminVisitorsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAcademicsRoute: AdminAcademicsRoute,
  AdminAdmissionsRoute: AdminAdmissionsRoute,
  AdminAiHubRoute: AdminAiHubRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCanteenRoute: AdminCanteenRoute,
  AdminCertificatesRoute: AdminCertificatesRoute,
  AdminCommunicationsRoute: AdminCommunicationsRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminExamsRoute: AdminExamsRoute,
  AdminFeesRoute: AdminFeesRoute,
  AdminHealthRoute: AdminHealthRoute,
  AdminHostelRoute: AdminHostelRoute,
  AdminHrRoute: AdminHrRoute,
  AdminInventoryRoute: AdminInventoryRoute,
  AdminLibraryRoute: AdminLibraryRoute,
  AdminSafetyRoute: AdminSafetyRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSportsRoute: AdminSportsRoute,
  AdminStaffRoute: AdminStaffRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminTransportRoute: AdminTransportRoute,
  AdminVisitorsRoute: AdminVisitorsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ParentRouteChildren {
  ParentAcademicsRoute: typeof ParentAcademicsRoute
  ParentAdmissionsRoute: typeof ParentAdmissionsRoute
  ParentFeesRoute: typeof ParentFeesRoute
  ParentNotificationsRoute: typeof ParentNotificationsRoute
  ParentTransportRoute: typeof ParentTransportRoute
  ParentIndexRoute: typeof ParentIndexRoute
}

const ParentRouteChildren: ParentRouteChildren = {
  ParentAcademicsRoute: ParentAcademicsRoute,
  ParentAdmissionsRoute: ParentAdmissionsRoute,
  ParentFeesRoute: ParentFeesRoute,
  ParentNotificationsRoute: ParentNotificationsRoute,
  ParentTransportRoute: ParentTransportRoute,
  ParentIndexRoute: ParentIndexRoute,
}

const ParentRouteWithChildren =
  ParentRoute._addFileChildren(ParentRouteChildren)

interface StudentRouteChildren {
  StudentAcademicsRoute: typeof StudentAcademicsRoute
  StudentAiHubRoute: typeof StudentAiHubRoute
  StudentAssignmentsRoute: typeof StudentAssignmentsRoute
  StudentCalendarRoute: typeof StudentCalendarRoute
  StudentFeedRoute: typeof StudentFeedRoute
  StudentFeesRoute: typeof StudentFeesRoute
  StudentMaterialsRoute: typeof StudentMaterialsRoute
  StudentNotificationsRoute: typeof StudentNotificationsRoute
  StudentProfileRoute: typeof StudentProfileRoute
  StudentSyllabusRoute: typeof StudentSyllabusRoute
  StudentTimetableRoute: typeof StudentTimetableRoute
  StudentTransportRoute: typeof StudentTransportRoute
  StudentIndexRoute: typeof StudentIndexRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentAcademicsRoute: StudentAcademicsRoute,
  StudentAiHubRoute: StudentAiHubRoute,
  StudentAssignmentsRoute: StudentAssignmentsRoute,
  StudentCalendarRoute: StudentCalendarRoute,
  StudentFeedRoute: StudentFeedRoute,
  StudentFeesRoute: StudentFeesRoute,
  StudentMaterialsRoute: StudentMaterialsRoute,
  StudentNotificationsRoute: StudentNotificationsRoute,
  StudentProfileRoute: StudentProfileRoute,
  StudentSyllabusRoute: StudentSyllabusRoute,
  StudentTimetableRoute: StudentTimetableRoute,
  StudentTransportRoute: StudentTransportRoute,
  StudentIndexRoute: StudentIndexRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

interface SuperAdminRouteChildren {
  SuperAdminConfigRoute: typeof SuperAdminConfigRoute
  SuperAdminDirectoryRoute: typeof SuperAdminDirectoryRoute
  SuperAdminHelpdeskRoute: typeof SuperAdminHelpdeskRoute
  SuperAdminIndexRoute: typeof SuperAdminIndexRoute
}

const SuperAdminRouteChildren: SuperAdminRouteChildren = {
  SuperAdminConfigRoute: SuperAdminConfigRoute,
  SuperAdminDirectoryRoute: SuperAdminDirectoryRoute,
  SuperAdminHelpdeskRoute: SuperAdminHelpdeskRoute,
  SuperAdminIndexRoute: SuperAdminIndexRoute,
}

const SuperAdminRouteWithChildren = SuperAdminRoute._addFileChildren(
  SuperAdminRouteChildren,
)

interface TeacherRouteChildren {
  TeacherAiHubRoute: typeof TeacherAiHubRoute
  TeacherAssignmentsRoute: typeof TeacherAssignmentsRoute
  TeacherAttendanceRoute: typeof TeacherAttendanceRoute
  TeacherExamsRoute: typeof TeacherExamsRoute
  TeacherFeedRoute: typeof TeacherFeedRoute
  TeacherFeesRoute: typeof TeacherFeesRoute
  TeacherLeaveRoute: typeof TeacherLeaveRoute
  TeacherLiveClassRoute: typeof TeacherLiveClassRoute
  TeacherMaterialsRoute: typeof TeacherMaterialsRoute
  TeacherMessagesRoute: typeof TeacherMessagesRoute
  TeacherProfileRoute: typeof TeacherProfileRoute
  TeacherReportsRoute: typeof TeacherReportsRoute
  TeacherSupportRoute: typeof TeacherSupportRoute
  TeacherSyllabusRoute: typeof TeacherSyllabusRoute
  TeacherIndexRoute: typeof TeacherIndexRoute
}

const TeacherRouteChildren: TeacherRouteChildren = {
  TeacherAiHubRoute: TeacherAiHubRoute,
  TeacherAssignmentsRoute: TeacherAssignmentsRoute,
  TeacherAttendanceRoute: TeacherAttendanceRoute,
  TeacherExamsRoute: TeacherExamsRoute,
  TeacherFeedRoute: TeacherFeedRoute,
  TeacherFeesRoute: TeacherFeesRoute,
  TeacherLeaveRoute: TeacherLeaveRoute,
  TeacherLiveClassRoute: TeacherLiveClassRoute,
  TeacherMaterialsRoute: TeacherMaterialsRoute,
  TeacherMessagesRoute: TeacherMessagesRoute,
  TeacherProfileRoute: TeacherProfileRoute,
  TeacherReportsRoute: TeacherReportsRoute,
  TeacherSupportRoute: TeacherSupportRoute,
  TeacherSyllabusRoute: TeacherSyllabusRoute,
  TeacherIndexRoute: TeacherIndexRoute,
}

const TeacherRouteWithChildren =
  TeacherRoute._addFileChildren(TeacherRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  ParentRoute: ParentRouteWithChildren,
  RegisterRoute: RegisterRoute,
  StudentRoute: StudentRouteWithChildren,
  SuperAdminRoute: SuperAdminRouteWithChildren,
  TeacherRoute: TeacherRouteWithChildren,
  DriverIndexRoute: DriverIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
